### ISSUE TITLE
Error looking up key in version 2.0.0

### ISSUE THREAD

**Issue by drmarconi** [crayfishx/hiera-http#40]
Hi,

There seems to be an issue looking up keys over http with version 2.0.0.

I perform hiera lookup with  'hiera -c hiera.yaml -d keyName' and get the following error:

```
/usr/lib/ruby/gems/1.8/gems/hiera-http-2.0.0/lib/hiera/backend/http_backend.rb:28: warning: multiple values for a block parameter (2 for 1)
        from /usr/lib/ruby/gems/1.8/gems/hiera-http-2.0.0/lib/hiera/backend/http_backend.rb:28
/usr/lib/ruby/gems/1.8/gems/hiera-http-2.0.0/lib/hiera/backend/http_backend.rb:28: warning: multiple values for a block parameter (2 for 1)
        from /usr/lib/ruby/gems/1.8/gems/hiera-http-2.0.0/lib/hiera/backend/http_backend.rb:28
/usr/lib/ruby/gems/1.8/gems/hiera-http-2.0.0/lib/hiera/backend/http_backend.rb:28: warning: multiple values for a block parameter (2 for 1)
        from /usr/lib/ruby/gems/1.8/gems/hiera-http-2.0.0/lib/hiera/backend/http_backend.rb:28
/usr/lib/ruby/gems/1.8/gems/hiera-http-2.0.0/lib/hiera/backend/http_backend.rb:28: warning: multiple values for a block parameter (2 for 1)
        from /usr/lib/ruby/gems/1.8/gems/hiera-http-2.0.0/lib/hiera/backend/http_backend.rb:28
/usr/lib/ruby/gems/1.8/gems/hiera-http-2.0.0/lib/hiera/backend/http_backend.rb:28: warning: multiple values for a block parameter (2 for 1)
        from /usr/lib/ruby/gems/1.8/gems/hiera-http-2.0.0/lib/hiera/backend/http_backend.rb:28
/usr/lib/ruby/gems/1.8/gems/hiera-http-2.0.0/lib/hiera/backend/http_backend.rb:30:in `initialize': undefined method `merge' for []:Array (NoMethodError)
        from /usr/lib/ruby/site_ruby/1.8/hiera/backend.rb:205:in `new'
        from /usr/lib/ruby/site_ruby/1.8/hiera/backend.rb:205:in `lookup'
        from /usr/lib/ruby/site_ruby/1.8/hiera/backend.rb:203:in `each'
        from /usr/lib/ruby/site_ruby/1.8/hiera/backend.rb:203:in `lookup'
        from /usr/lib/ruby/site_ruby/1.8/hiera.rb:60:in `lookup'
        from /usr/bin/hiera:225
```
This doesn't happen in hiera-http version 1.4.0. I am using ruby version 1.8.7.

**Comment by xescab** [comment]
I get the same error, and version 1.4.0 does not work for me because I need to pass a token to the HTTP API. Please fix this. Thanks!

**Comment by crayfishx** [comment]
@drmarconi @xescab Can you show your configuration from hiera.yaml please?

**Comment by drmarconi** [comment]
Hi,

My hiera config would be as follows:

```
:http:
    :host: <ip_address>
    :port: <port>
    :output: json
    :failure: graceful
    :paths:
        - /path/to/endpoint
```

Thanks
